version: '3.8'

services:
  foro-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./frontend:/usr/src/frontend # Montamos el frontend para que Express lo sirva estáticamente
      - ./backend:/usr/src/app # Montamos el backend para desarrollo
      # Nota: En un entorno de producción real, el frontend se copiaría dentro de una imagen de Nginx
      # y no se montarían volúmenes locales de código, pero para este Hackathon esto facilita la evaluación.
